// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 12 Sep 2019 01:42:04 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package pugl provides Go bindings for pugl
*/
package pugl
