// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 05 Sep 2019 16:02:53 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <lv2/lv2plug.in/ns/lv2core/lv2.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

