// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 05 Sep 2019 15:48:59 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package lv2 provides Go bindings for LV2
*/
package lv2
